version: 0.0.1.{build}-test

shallow_clone: true

environment:
  LUAROCKS_VER: 2.4.1
  LUA_VER: 5.1.5

matrix:
  allow_failures:
    - configuration: 2010
      platform: x64
    - configuration: 2008
      platform: x64
    - configuration: MinGW
      platform: x64

platform:
  - x86
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

# Skip unsupported combinations (ie, VS2008 for x64 is not supported)
init:
- if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )


install:
# Make compiler command line tools available
- call .appveyor\set_compiler_env.bat
# Setup Lua development/build environment
- call .appveyor\install.bat

build_script:
  - luarocks install https://raw.githubusercontent.com/lidesdk/framework/master/lide-0.0-0.rockspec
  - luarocks install luafilesystem

test_script:
- echo "Testing..."
- set LIDE_FRAMEWORK=%CD%
- lua tests/exec_test.lua
- lide search alien
#- luacheck --std max+buted src spec
#- busted --verbose --coverage

#after_test:
#  - if "%LUA_VER:~0,3%"=="5.1" (luarocks show bit32 || luarocks install bit32)
#  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
#  - luacov-coveralls -v -e c:\lua -c spec\.luacov