version: 0.0.1.{build}-test

shallow_clone: true

environment:
  LUAROCKS_VER: 2.4.1
  LUA_VER: 5.1.5

platform:
  - x86

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

install:
# Make compiler command line tools available
- call .appveyor\set_compiler_env.bat
# Setup Lua development/build environment
- call .appveyor\install.bat

build_script:
  - luarocks install --local luafilesystem
  - luarocks install --local https://raw.githubusercontent.com/lidesdk/framework/master/lide-0.0-0.rockspec

test_script:
- set LIDE_FRAMEWORK=c:\lua\%platform%\5.1.5\LuaRocks\systree\share\lua\5.1\lide
- set LIDE_PATH=%CD%
- lua tests\exec_test.lua